### ISSUE TITLE
The plugin doesn't load in QGIS Versione di QGIS 3.28.3-Firenze  c12bcb2f76 on Ubuntu 22.04

### ISSUE THREAD

**Issue by Antoviscomi** [jeremyk6/qdraw#14]
Hi  @jeremyk6 ,
when I try to install the plugin, I receive that follow:

Impossibile caricare il plugin 'qdraw' a causa di un errore chiamando il metodo classFactory() 

TypeError: arguments did not match any overloaded call:   move(self, QPoint): argument 1 has unexpected type 'float'   move(self, int, int): argument 1 has unexpected type 'float' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/antonio/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qdraw/__init__.py", line 22, in classFactory
    return Qdraw(iface)
  File "/home/antonio/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qdraw/qdraw.py", line 78, in __init__
    self.settings = QdrawSettings()
  File "/home/antonio/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qdraw/qdrawsettings.py", line 36, in __init__
    self.center()
  File "/home/antonio/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qdraw/qdrawsettings.py", line 81, in center
    self.move((screen.width() - size.width()) / 2,
TypeError: arguments did not match any overloaded call:
  move(self, QPoint): argument 1 has unexpected type 'float'
  move(self, int, int): argument 1 has unexpected type 'float'

Versione Python: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] 
Versione di QGIS: 3.28.2-Firenze Firenze, b47e00ba60 

Percorso Python:
/home/antonio/.local/share/QGIS/QGIS3/profiles/default/python/plugins/dissect_dissolve_overlaps
/home/antonio/.local/share/QGIS/QGIS3/profiles/default/python/plugins/clusterpoints
/usr/share/qgis/python
/home/antonio/.local/share/QGIS/QGIS3/profiles/default/python
/home/antonio/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python310.zip
/usr/lib/python3.10
/usr/lib/python3.10/lib-dynload
/home/antonio/.local/lib/python3.10/site-packages
/usr/local/lib/python3.10/dist-packages
/usr/lib/python3/dist-packages
/home/antonio/.local/share/QGIS/QGIS3/profiles/default/python
/home/antonio/.local/share/QGIS/QGIS3/profiles/default/python/plugins/postgisQueryBuilder
/home/antonio/.local/share/QGIS/QGIS3/profiles/default/python/plugins/postgisQueryBuilder/extlibs
/home/antonio/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2streetview
/home/antonio/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2streetview/res
/home/antonio/.local/share/QGIS/QGIS3/profiles/default/python/plugins/HouseNumbering3/forms
/home/antonio/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DeepLearningTools
/home/antonio/.local/share/QGIS/QGIS3/profiles/default/python/plugins/shapetools/ext-libs
.

**Comment by joaomanaia** [comment]
I fixed this issue but the owner didn't updated the version in qgis repository, you can download the [Source code](https://github.com/jeremyk6/qdraw/archive/refs/heads/master.zip) of qdraw and add a new plugin from the zip file you downloaded, like this:

![Add plugin from zip example](https://user-images.githubusercontent.com/53819675/216852468-c96a5b00-2ca5-4a4b-a4e2-afccfe8e0228.png)

**Comment by Antoviscomi** [comment]
after the update of the plugin all works fine, so I close this issue
