### ISSUE TITLE
Plantage si le projet contient une couche ouverte avec Quickmapservice

### ISSUE THREAD

**Issue by IsabelleGiraud** [jeremyk6/qdraw#5]
Bonjour

je souhaite utiliser votre extension bien pratique mais mon projet affiche des couches Google ouvertes avec l'extension QuickMapService ce qui entraine le message d'erreur ci-dessous.

Je n'ai pas de problème si je supprime les couches ouvertes avec QuickMapService (Google Satellite, Trafic et Roads).

Merci

Une erreur est survenue lors de l'éxécution du code Python: 

AttributeError: 'TileLayer' object has no attribute 'dataProvider' 
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS\profil/python/plugins\qdraw\qdraw.py", line 423, in draw
    name, add, index, layers, ok = QDrawLayerDialog(self.iface, self.drawShape).getName(self.iface, self.drawShape)
  File "C:\PROGRA~1\QGIS\profil/python/plugins\qdraw\qdrawlayerdialog.py", line 41, in __init__
    if "memory" in layer.dataProvider().dataSourceUri()[:6]: # must be a memory layer
AttributeError: 'TileLayer' object has no attribute 'dataProvider'

Version de Python : 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
Version de QGIS : 2.16.3 Nødebo, 7d00cae 

Chemin Python :
C:/PROGRA~1/QGIS/apps/qgis/./python/plugins\processing
C:/PROGRA~1/QGIS/apps/qgis/./python
C:\PROGRA~1\QGIS\profil/python
C:\PROGRA~1\QGIS\profil/python/plugins
C:/PROGRA~1/QGIS/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS\apps\Python27\lib\site-packages\setuptools-0.9.8-py2.7.egg
C:\PROGRA~1\QGIS\bin\python27.zip
C:\PROGRA~1\QGIS\apps\Python27\DLLs
C:\PROGRA~1\QGIS\apps\Python27\lib
C:\PROGRA~1\QGIS\apps\Python27\lib\plat-win
C:\PROGRA~1\QGIS\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGIS\bin
C:\PROGRA~1\QGIS\apps\Python27
c:\progra~1\qgis\apps\python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
c:\progra~1\qgis\apps\python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
c:\progra~1\qgis\apps\python27\lib\site-packages\owslib-0.7.2-py2.7.egg
c:\progra~1\qgis\apps\python27\lib\site-packages\pytz-2012j-py2.7.egg
c:\progra~1\qgis\apps\python27\lib\site-packages\shapely-1.2.18-py2.7-win-amd64.egg
c:\progra~1\qgis\apps\python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
c:\progra~1\qgis\apps\python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:\PROGRA~1\QGIS\apps\Python27\lib\site-packages
C:\PROGRA~1\QGIS\apps\Python27\lib\site-packages\PIL
C:\PROGRA~1\QGIS\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGIS\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGIS\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGIS\profil/python
Y:/6-Applications/QGIS/5-Projet

**Comment by IsabelleGiraud** [comment]
J'ai oublié de préciser que j'utilise Qgis 2.16. QDraw ne plante pas en 3.4 avec QuickMapService.

Nous n'avons pas encore migré nos postes. Est-il possible de télécharger une version compatible en 2.16?

Merci

**Comment by jeremyk6** [comment]
Bonjour,

C'est corrigé (https://github.com/jeremyk6/qdraw/commit/5c315d7169ef23f62a4b3564c08000b8b88c64e5). Une nouvelle version pour QGIS 2.X est attente de validation dans le dépôt de plugins, cela ne prend souvent que quelques heures. En attendant, vous pouvez désinstaller l'ancienne version et installer la nouvelle à partir du [zip](https://github.com/jeremyk6/qdraw/archive/2.X.zip) si vous le souhaitez.

Merci de m'avoir remonté le bug. N'hésitez pas si vous rencontrez d'autres problèmes ou avez des idées d'améliorations.

Cordialement.

**Comment by IsabelleGiraud** [comment]
Bonjour et merci pour votre réactivité.
      
      Pour les idées d'amélioration, j'en ai 2:
      - la possibilité de choisir un style de flèche au lieu d'un trait
      basique directement depuis le petit menu déroulant
      - la possibilité de rajouter du texte au lieu d'utiliser les
      possibilité d'annotation de Qgis.
      
      Je crois avoir compris que vous avez aussi développé Qgéric?
      
      Je l'ai testé et c'est absolument parfait pour mes collègues qui
      instruisent toutes sortes de dossiers. J'ai prévu de le déployer
      rapidement mais c'est dommage que personne n'en fasse la pub
      surtout que c'est hyper intéressant bien au delà de la gestion de
      crise! et beaucoup plus simple à utiliser que l'ancien Select plus
      pour des utilisateurs basiques.
      
      Je travaille entre autre sur des PC gestion de crise pour nos
      cadres de permanence et ce genre d'outils comble un grand manque!
      
      Un grand merci
      
    
    
      
      
      
      
      
      
	
	
      Cordialement,

Isabelle GIRAUD

Direction Départementale des Territoires et de la Mer 34
Service Eau-Risques et Nature 
Prévention des risques naturels  et technologiques
Tel: 04 34 46 60 08 
      
        Bâtiment
                  Ozone 
                  181 Place Ernest Granier 
                  CS 60556 
                  34 064
                  Montpellier Cedex
          2
                
      
      Site
                      internet des services de l’État dans l’Hérault
      
      
      
      
      
        
      
      
      
      
        
      
    
    Le 22/07/2019 à 15:06, > jeremyk6
      (par Internet, dépôt
      bounces+848413-cb16-isabelle.giraud=herault.gouv.fr@sgmail.github.com)
      a écrit :
    
    
      Bonjour,
      C'est corrigé (5c315d7).
        Une nouvelle version pour QGIS 2.X est attente de validation
        dans le dépôt de plugins, cela ne prend souvent que quelques
        heures. En attendant, vous pouvez désinstaller l'ancienne
        version et installer la nouvelle à partir du zip
        si vous le souhaitez.
      Merci de m'avoir remonté le bug. N'hésitez pas si vous
        rencontrez d'autres problèmes ou avez des idées d'améliorations.
      Cordialement.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      [

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/jeremyk6/qdraw/issues/5?email_source=notifications\u0026email_token=AMVVAA6IB6SIR26IJ7WDK7DQAWWFXA5CNFSM4IFV7OOKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2P3KYQ#issuecomment-513783138",

"url": "https://github.com/jeremyk6/qdraw/issues/5?email_source=notifications\u0026email_token=AMVVAA6IB6SIR26IJ7WDK7DQAWWFXA5CNFSM4IFV7OOKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2P3KYQ#issuecomment-513783138",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by jeremyk6** [comment]
> la possibilité de choisir un style de flèche au lieu d'un trait basique directement depuis le petit menu déroulant

Je voulais limiter les variations de style dans le plugin à la couleur et à l'opacité comme la gestion plus poussée du style peut se faire facilement depuis les paramètres de la couche, et pour maintenir la simplicité d'utilisation. Cependant c'est une bonne idée, notamment en gestion de crise. Je vais réfléchir à une manière de l'implémenter.

> la possibilité de rajouter du texte au lieu d'utiliser les possibilité d'annotation de Qgis.

Un utilisateur m'a soumis une contribution d'étiquetage automatique du dessin avec son attribut il y a quelques temps. Cela fait partie des modifications que je veux intégrer à la prochaine version. Pour les annotations textes, l'outil de QGIS nous semblait suffisamment simple pour nos besoins. J'ai cependant développé [annotationManager](http://plugins.qgis.org/plugins/annotationManager/) pour pouvoir gérer leur affichage à la manière des couches.

> Je crois avoir compris que vous avez aussi développé Qgéric?

Oui, je l'ai d'ailleurs aussi porté sous QGIS 3 il y a peu de temps. De la même manière, n'hésitez pas à me remonter bugs et idées d'amélioration !

Merci pour votre retour !

Cordialement.

**Comment by IsabelleGiraud** [comment]
Bonjour Jérémy
      
      j'ai un nouveau problème ce matin.
      J'ai installé Qdraw sur 2 PC portables avec la même config Qgis
      que mon poste fixe et l'extension plante sans message d'erreur.
      
      Elle se fige sur la fenêtre de saisie du nom de la couche et plus
      rien de ne se passe et Qgis plante quand on essaie de sortir de
      l'outil.
      
      Merci
       
    
    
      
      
      
      
      
      
	
	
      Cordialement,

Isabelle GIRAUD

Direction Départementale des Territoires et de la Mer 34
Service Eau-Risques et Nature 
Prévention des risques naturels  et technologiques
Tel: 04 34 46 60 08 
      
        Bâtiment
                  Ozone 
                  181 Place Ernest Granier 
                  CS 60556 
                  34 064
                  Montpellier Cedex
          2
                
      
      Site
                      internet des services de l’État dans l’Hérault
      
      
      
      
      
        
      
      
      
      
        
      
    
    Le 22/07/2019 à 16:20, > jeremyk6
      (par Internet, dépôt
      bounces+848413-cb16-isabelle.giraud=herault.gouv.fr@sgmail.github.com)
      a écrit :
    
    
      
        la possibilité de choisir un style de flèche au lieu d'un
          trait basique directement depuis le petit menu déroulant
      
      Je voulais limiter les variations de style dans le plugin à la
        couleur et à l'opacité comme la gestion plus poussée du style
        peut se faire facilement depuis les paramètres de la couche, et
        pour maintenir la simplicité d'utilisation. Cependant c'est une
        bonne idée, notamment en gestion de crise. Je vais réfléchir à
        une manière de l'implémenter.
      
        la possibilité de rajouter du texte au lieu d'utiliser les
          possibilité d'annotation de Qgis.
      
      Un utilisateur m'a soumis une contribution d'étiquetage
        automatique du dessin avec son attribut il y a quelques temps.
        Cela fait partie des modifications que je veux intégrer à la
        prochaine version. Pour les annotations textes, l'outil de QGIS
        nous semblait suffisamment simple pour nos besoins. J'ai
        cependant développé annotationManager pour pouvoir gérer leur
        affichage à la manière des couches.
      
        Je crois avoir compris que vous avez aussi développé Qgéric?
      
      Oui, je l'ai d'ailleurs aussi porté sous QGIS 3 il y a peu de
        temps. De la même manière, n'hésitez pas à me remonter bugs et
        idées d'amélioration !
      Merci pour votre retour !
      Cordialement.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      [

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/jeremyk6/qdraw/issues/5?email_source=notifications\u0026email_token=AMVVAAYK5G3EBV4BMHSWRX3QAW6Y3A5CNFSM4IFV7OOKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2QCKPI#issuecomment-513811773",

"url": "https://github.com/jeremyk6/qdraw/issues/5?email_source=notifications\u0026email_token=AMVVAAYK5G3EBV4BMHSWRX3QAW6Y3A5CNFSM4IFV7OOKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2QCKPI#issuecomment-513811773",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by jeremyk6** [comment]
Bonjour,

S'agit-il toujours de la version 2.16 de QGIS ? Quels types de couches sont ouvertes dans QGIS lorsque l'erreur se produit ?

Cordialement.

**Comment by IsabelleGiraud** [comment]
Oui c'est bien en 2.16.
      
      J'ouvre le même projet que sur mon poste fixe où l'extension
      fonctionne.
      
      Je n'ai pas les droits d'administrateur pour installer la 3.4 sur
      le portable pour faire un test.
      
      L'extension plante même si j'ouvre 1 seule couche et que je
      désinstalle Quickmapservice.
      
      J'ai désinstallé toutes les extensions que je pouvais et gardé
      actives les indispensables qui sont aussi sur mon poste fixe.
      
      
      
      
    
    
      
      
      
      
      
      
	
	
      Cordialement,

Isabelle GIRAUD

Direction Départementale des Territoires et de la Mer 34
Service Eau-Risques et Nature 
Prévention des risques naturels  et technologiques
Tel: 04 34 46 60 08 
      
        Bâtiment
                  Ozone 
                  181 Place Ernest Granier 
                  CS 60556 
                  34 064
                  Montpellier Cedex
          2
                
      
      Site
                      internet des services de l’État dans l’Hérault
      
      
      
      
      
        
      
      
      
      
        
      
    
    Le 23/07/2019 à 16:59, > jeremyk6
      (par Internet, dépôt
      bounces+848413-cb16-isabelle.giraud=herault.gouv.fr@sgmail.github.com)
      a écrit :
    
    
      Bonjour,
      S'agit-il toujours de la version 2.16 de QGIS ? Quels types de
        couches sont ouvertes dans QGIS lorsque l'erreur se produit ?
      Cordialement.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jeremyk6/qdraw/issues/5?email_source=notifications\u0026email_token=AMVVAA3SMXXHDE3KTYGMHV3QA4MGRA5CNFSM4IFV7OOKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2TM6TA#issuecomment-514248524",
"url": "https://github.com/jeremyk6/qdraw/issues/5?email_source=notifications\u0026email_token=AMVVAA3SMXXHDE3KTYGMHV3QA4MGRA5CNFSM4IFV7OOKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2TM6TA#issuecomment-514248524",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jeremyk6** [comment]
Bonjour,

Je suis désolé, j'ai fait plusieurs tests en 2.16 de mon côté et je n'ai pas réussi à reproduire le problème. Est-ce la dernière révision de la 2.16 (2.16.3) ? Je crois avoir rencontré un bug similaire à l'époque, réglé par une mise à jour de QGIS. Vous pouvez peut-être aussi tenter de supprimer votre profil QGIS (dossier caché .qgis2 dans C:\Users\[nom_de_l'utilisateur]) si vous ne l'avez pas personnalisé.

**Comment by IsabelleGiraud** [comment]
Bonjour
      
      les versions de Qgis sont les mêmes mais je vais creuser le pb du
      profil qui est particulier sur les portables car adapté à des
      utilisateurs "non experts".
      S'il faut je mettrai la version 3.4.
      
      Je vous tiens au courant si je trouve quelque chose, merci d'avoir
      cherché quand même.
    
    
      
      
      
      
      
      
	
	
      Cordialement,

Isabelle GIRAUD

Direction Départementale des Territoires et de la Mer 34
Service Eau-Risques et Nature 
Prévention des risques naturels  et technologiques
Tel: 04 34 46 60 08 
      
        Bâtiment
                  Ozone 
                  181 Place Ernest Granier 
                  CS 60556 
                  34 064
                  Montpellier Cedex
          2
                
      
      Site
                      internet des services de l’État dans l’Hérault
      
      
      
      
      
        
      
      
      
      
        
      
    
    Le 24/07/2019 à 19:08, > jeremyk6
      (par Internet, dépôt
      bounces+848413-cb16-isabelle.giraud=herault.gouv.fr@sgmail.github.com)
      a écrit :
    
    
      Bonjour,
      Je suis désolé, j'ai fait plusieurs tests en 2.16 de mon côté
        et je n'ai pas réussi à reproduire le problème. Est-ce la
        dernière révision de la 2.16 (2.16.3) ? Je crois avoir rencontré
        un bug similaire à l'époque, réglé par une mise à jour de QGIS.
        Vous pouvez peut-être aussi tenter de supprimer votre profil
        QGIS (dossier caché .qgis2 dans C:\Users[nom_de_l'utilisateur])
        si vous ne l'avez pas personnalisé.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      [

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/jeremyk6/qdraw/issues/5?email_source=notifications\u0026email_token=AMVVAA7VCISWC6KYUEUYLRLQBCEAPA5CNFSM4IFV7OOKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2W7WXI#issuecomment-514718557",

"url": "https://github.com/jeremyk6/qdraw/issues/5?email_source=notifications\u0026email_token=AMVVAA7VCISWC6KYUEUYLRLQBCEAPA5CNFSM4IFV7OOKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2W7WXI#issuecomment-514718557",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
