### ISSUE TITLE
TypeError: 'QVariant' object is not subscriptable

### ISSUE THREAD

**Issue by PhilippeD31** [jeremyk6/qdraw#7]
Bonjour,
au chargement du plugin (avec QGIS 3.10 et 3.16), j'ai un message d'erreur :  
```python
qdraw.py", line 47, in init
locale = QSettings().value('locale/userLocale')[0:2]
TypeError: 'QVariant' object is not subscriptable
```

C'est un soucis que j'ai déjà rencontré. Pour le régler, on peut remplacer la ligne par :  
```python
overrideLocale= QSettings().value("locale/overrideFlag", False, type=bool)
if not overrideLocale:  locale= QLocale.system().name()
else:
    locale= QSettings().value("locale/userLocale", "")
    if locale.__class__.__name__=='QVariant': locale= 'en'
locale= locale[0:2]
```
Merci !

**Comment by jeremyk6** [comment]
Bonjour,

Je viens d'effectuer la modification (https://github.com/jeremyk6/qdraw/commit/d400401eff581df55ff50dcecd1433db2387a20c), cependant je n'ai jamais rencontré le souci que ce soit sous Windows 10 ou sous Ubuntu. Quel est votre environnement ?

Bonne journée !

**Comment by PhilippeD31** [comment]
Bonjour  
j'ai rencontré ce soucis sur QGIS 3.16.9 sous Win 10, juste après l'installation de Qdraw.  
Mais j'avais eu ce bug plusieurs fois avec d'autres plugins. C'est depuis QGIS 3.10 ou 3.4. J'avais dû corriger mes plugins avec le "patch" ci-dessus.  
C'est un peu aléatoire. Parfois QSettings().value('locale/userLocale') retourne un QVariant...  
Merci pour la correction !
